DATASPINE_MODEL_NAME=ccfd \
DATASPINE_MODEL_TAG=v1 \
DATASPINE_MODEL_TYPE=keras \
DATASPINE_MODEL_RUNTIME=python \
DATASPINE_MODEL_CHIP=cpu \
DATASPINE_INPUT_PATH=../input \
DATASPINE_OUTPUT_PATH=../output \
  python dataspine_predict.py
