DATASPINE_MODEL_NAME=resnet50 \
DATASPINE_MODEL_TAG=cpu \
DATASPINE_MODEL_TYPE=keras \
DATASPINE_MODEL_RUNTIME=python \
DATASPINE_MODEL_CHIP=chip \
DATASPINE_INPUT_PATH=../input \
DATASPINE_OUTPUT_PATH=. \
  python dataspine_train.py
