DATASPINE_MODEL_NAME=inception \
DATASPINE_MODEL_TAG=cpu \
DATASPINE_MODEL_TYPE=tensorflow \
DATASPINE_MODEL_RUNTIME=tfserving \
DATASPINE_MODEL_CHIP=cpu \
DATASPINE_INPUT_PATH= \
DATASPINE_OUTPUT_PATH= \
  python dataspine_predict.py