DATASPINE_MODEL_NAME=zscore \
DATASPINE_MODEL_TAG=cpu \
DATASPINE_MODEL_TYPE=python \
DATASPINE_MODEL_RUNTIME=python \
DATASPINE_MODEL_CHIP=cpu \
DATASPINE_INPUT_PATH=../input \
DATASPINE_OUTPUT_PATH=../output \
  python dataspine_predict.py
